Feature/credential-mint
Gateway-DAO/ui pull request #104
Opened 2022-08-16 12:25 UTC by NunoMartins21

# Feature/credential-mint

## Type of PR

- [x] - feature

## Description

Allow users to mint subsidized credential NFTs if they complete a gate/credential on the platform

2022-08-16 13:02 UTC, rafagomes approved these changes
Only the console.log, but is not blocking

2022-08-16 13:02 UTC, rafagomes commented on apps/website/hooks/use-mint.tsx
>            console.log(
Is this console.log really necessary?

2022-08-16 13:30 UTC, NunoMartins21 commented on apps/website/hooks/use-mint.tsx
>            console.log(
It's never necessary haha. We were just checking for normal vs subsidized transactions, but I'll remove it!

2022-08-19 11:56 UTC, fbenfraj requested changes

2022-08-19 11:56 UTC, fbenfraj commented on apps/website/components/organisms/mint-modal/mint-select.tsx
> +      {/* {error && <div>{error.message}</div>} */}
Remove comment

2022-08-19 11:56 UTC, fbenfraj commented on apps/website/components/templates/profile/tabs/OverviewTab.tsx
> +      //section: <ActivityTab />,
Remove ?

2022-08-19 11:56 UTC, fbenfraj commented on apps/website/providers/biconomy/context.ts
> +// export const BiconomyContext = createContext<Context>({
Remove

2022-08-19 13:55 UTC, rafagomes commented on apps/website/components/molecules/mint-card/screen/default-mint-screen.tsx
> +                rel="noreferrer"
just to let you know...the new application on the browsers, add this automatically. Is not necessary anymore...

2022-09-06 15:14 UTC, NunoMartins21 commented on apps/website/providers/biconomy/context.ts
> +// export const BiconomyContext = createContext<Context>({
Fixed

2022-09-06 15:14 UTC, NunoMartins21 commented on apps/website/components/templates/profile/tabs/OverviewTab.tsx
> +      //section: <ActivityTab />,
Fixed

2022-09-06 15:15 UTC, NunoMartins21 commented on apps/website/components/organisms/mint-modal/mint-select.tsx
> +      {/* {error && <div>{error.message}</div>} */}
Fixed

2022-09-06 15:17 UTC, merged