fixing button still visible on task completion
Gateway-DAO/ui pull request #107
Opened 2022-08-17 14:28 UTC by rafagomes

# Fixing Buttons still visible on Gate viewing

## Type of PR

- [x] - bugfix

## Description
Fixing all buttons still visible on tasks completion.

##Refers to
https://app.asana.com/0/1202770668722101/1202802746676884/f
https://app.asana.com/0/1202770668722101/1202802746676877/f
https://app.asana.com/0/1202770668722101/1202802746676868/f

2022-08-19 09:00 UTC, NunoMartins21 approved these changes

2022-08-19 09:28 UTC, fbenfraj approved these changes

2022-08-22 15:25 UTC, kbooz requested changes

2022-08-22 15:25 UTC, kbooz commented on apps/website/components/organisms/tasks/task-error-messages.ts
> +export const taskErrorMessages = {
move it to locales

2022-08-23 12:24 UTC, merged