Feat/draft gate
Gateway-DAO/ui pull request #109
Opened 2022-08-19 15:01 UTC by fbenfraj

# Feat/draft gate

## Type of PR
- [✅ ] - feature

## Included in this PR:
- Gate State Chip component added to GateCards and CategoriesLists
- "More" Popover component for Gate options (delete, edit...)
- Confirmation Dialog component on publish/unpublish or delete
- Create Gate: Loads draft data to the form
- Redirections to correct pages depending on gate_state
- Rename create-navbar to publish-navbar
- Save as Draft logic with validation
- Refactor of the createGate function (fused with saveDraft into handleMutation)
- Added DraftGateTypes type schema (since tasks format is different when we send it to the database `tasks: { data: [...]}` and when we retrieve it `tasks: [ ]`)
- Fixes for long descriptions breaking the visuals and usage of ReadMore
- Filtering unpublished gates on Explore page (TODO: move this logic to backend)
- View Gate: Edit, Publish/Unpublish and Delete logic
- View Gate: Remove instant completion on gate view when there is no tasks on Draft
- Update queries on_conflict and mutations

2022-08-22 14:12 UTC, rafagomes requested changes

2022-08-22 15:23 UTC, kbooz requested changes

2022-09-05 22:20 UTC, kbooz requested changes

2022-09-05 22:20 UTC, kbooz commented on apps/website/components/atoms/more-popover.tsx
> +                  onClick={option.action}
Onclick on a non-button component

2022-09-05 22:20 UTC, kbooz commented on apps/website/components/atoms/more-popover.tsx
> +const MorePopover = ({ options }) => {
Missing prop types

2022-09-05 22:20 UTC, kbooz commented on apps/website/components/molecules/categories-input.tsx
> +export const CategoriesInput = ({ set, defaultValue, ...props }) => {
Missing prop types

2022-09-05 22:20 UTC, kbooz commented on apps/website/components/molecules/skills-input.tsx
> +export const SkillsInput = ({ set, defaultValue, ...props }) => {
Missing prop types

2022-09-05 22:20 UTC, kbooz commented on apps/website/components/organisms/confirm-dialog/confirm-dialog.tsx
> +const ConfirmDialog = (props) => {
missing prop types

2022-09-05 22:20 UTC, kbooz commented on apps/website/components/organisms/gates/create/gate-published.tsx
> +export default function GatePublishedModal({ gateId, open, handleClose }) {
Missing prop types

2022-09-05 22:20 UTC, kbooz commented on apps/website/components/organisms/tasks-area/tasks-area.tsx
> +const TaskArea = ({ draftTasks, onDelete }) => {
Missing prop types

2022-09-05 22:20 UTC, kbooz commented on apps/website/pages/gate/new.tsx
> +export default function CreateGate({ gateProps }) {
Missing prop types

2022-09-06 12:39 UTC, fbenfraj commented on apps/website/pages/gate/new.tsx
> +export default function CreateGate({ gateProps }) {
Added

2022-09-06 12:39 UTC, fbenfraj commented on apps/website/components/organisms/gates/create/gate-published.tsx
> +export default function GatePublishedModal({ gateId, open, handleClose }) {
Added

2022-09-06 12:39 UTC, fbenfraj commented on apps/website/components/organisms/confirm-dialog/confirm-dialog.tsx
> +const ConfirmDialog = (props) => {
Added

2022-09-06 12:39 UTC, fbenfraj commented on apps/website/components/molecules/skills-input.tsx
> +export const SkillsInput = ({ set, defaultValue, ...props }) => {
Added

2022-09-06 12:39 UTC, fbenfraj commented on apps/website/components/molecules/categories-input.tsx
> +export const CategoriesInput = ({ set, defaultValue, ...props }) => {
Added

2022-09-06 12:39 UTC, fbenfraj commented on apps/website/components/atoms/more-popover.tsx
> +const MorePopover = ({ options }) => {
Added

2022-09-06 13:11 UTC, fbenfraj commented on apps/website/components/atoms/more-popover.tsx
> +                  onClick={option.action}
Fixed

2022-09-06 13:50 UTC, NunoMartins21 approved these changes
Seems like everything is good to go

2022-09-06 15:09 UTC, merged