Fixing/task self verify flow
Gateway-DAO/ui pull request #121
Opened 2022-09-02 14:35 UTC by R11manish

# New Flow For Self Verify Task

## Type of PR

- [x] - feature
- [x] - bugfix

## Description
- [x] - Add a container contained the list of links, like a card component.
- [x] - Add a button next to the link. The button label must be "View".
- [x] - If the user has not clicked on the view button. The button must be filled.
- [x] - If the user has clicked on the view button. The button must be outlined.
- [x] - Change the button label "Submit" to "Done"
- [x] - The Done button is enabled only if the user clicks on all links.

[ASANA LINK](https://app.asana.com/0/1202416027350476/1202883812736614/f)

2022-09-02 14:42 UTC, rafagomes commented on apps/website/components/organisms/gates/view/tasks/content/self-verify.tsx
> +    <Button
Use link instead of Button and add the logic in the onClick. It will remove the entire window.open.

2022-09-02 15:43 UTC, R11manish commented on apps/website/components/organisms/gates/view/tasks/content/self-verify.tsx
> +    <Button
done

2022-09-02 17:38 UTC, rafagomes commented on apps/website/components/organisms/gates/view/tasks/content/self-verify.tsx
> +      <Button
never use button for that...use TYPOGRAPHY.

2022-09-05 14:14 UTC, kbooz requested changes

2022-09-05 14:14 UTC, kbooz commented on apps/website/components/organisms/gates/view/tasks/content/self-verify.tsx
> +          Task completed at {formattedDate}
put the content inside `locales`

2022-09-05 14:14 UTC, kbooz commented on apps/website/components/organisms/gates/view/tasks/content/self-verify.tsx
> +          Done
put the content inside locales

2022-09-06 15:24 UTC, NunoMartins21 commented on apps/website/components/organisms/gates/view/tasks/content/self-verify.tsx
> +          Done
I'm referencing that on issue #124. I don't consider that to be a top priority when we have a refactor coming.

2022-09-06 15:24 UTC, merged