profile editing pages
Gateway-DAO/ui pull request #13
Opened 2022-06-03 07:59 UTC by Ashishgy

# Profile Editing 

- [] - Added Profile Edit , Edit Skills, Edit Attitude, Edit Knowledge

## Description

Added the pages with all the functionality of Edit User profile. 

## Checklist

- Tested on all the devices.

2022-06-03 14:41 UTC, fbenfraj requested changes

2022-06-03 14:41 UTC, fbenfraj commented on apps/website/pages/profile/edit-attitudes.tsx
> +
Why all the space jumps? 😄

2022-06-03 14:41 UTC, fbenfraj commented on apps/website/pages/profile/edit-attitudes.tsx
> +    const [arr, setArr] = useState([]);
Give more specific name than arr if possible

2022-06-03 14:41 UTC, fbenfraj commented on apps/website/pages/profile/edit-knowledge.tsx
> +    const [arr, setArr] = useState([]);
Give more specific name than arr if possible

2022-06-03 14:41 UTC, fbenfraj commented on apps/website/pages/profile/edit-profile.tsx
> +    useEffect(() => {
I think we have a JWT session system, no need to use the localStorage
For more details you might want to talk with @kbooz 😄

2022-06-03 14:41 UTC, fbenfraj commented on apps/website/pages/profile/edit-skills.tsx
> +    const [arr, setArr] = useState([]);
Give more specific name than arr if possible

2022-06-03 14:41 UTC, fbenfraj commented on apps/website/pages/profile/edit-profile.tsx
> +            const reader = new FileReader();
Not sure why we need this

2022-06-06 19:59 UTC, Ashishgy commented on apps/website/pages/profile/edit-attitudes.tsx
> +
Probably because of removing comments, Have changed now

2022-06-06 19:59 UTC, Ashishgy commented on apps/website/pages/profile/edit-attitudes.tsx
> +    const [arr, setArr] = useState([]);
Change to attitudes

2022-06-06 19:59 UTC, Ashishgy commented on apps/website/pages/profile/edit-knowledge.tsx
> +    const [arr, setArr] = useState([]);
change to Knowledge

2022-06-06 20:00 UTC, Ashishgy commented on apps/website/pages/profile/edit-skills.tsx
> +    const [arr, setArr] = useState([]);
Changed to skills

2022-06-13 11:21 UTC, merged