Feat/gate card options
Gateway-DAO/ui pull request #144
Opened 2022-09-09 14:37 UTC by fbenfraj

# [PR Name]
gate card options

## Type of PR
- [] - feature

## Description
DAO Profile (as Admin) > Credentials tab > Gate Cards

2022-09-09 14:56 UTC, kbooz requested changes

2022-09-09 14:56 UTC, kbooz commented on apps/website/components/molecules/gates-card.tsx
> +            message: 'Credential deleted!',
put content on locales

2022-09-09 14:56 UTC, kbooz commented on apps/website/components/molecules/gates-card.tsx
> +                : 'unpublished!'
put content on locales

2022-09-09 14:56 UTC, kbooz commented on apps/website/components/molecules/gates-card.tsx
> +      text: 'Delete',
put content on locales

2022-09-09 14:56 UTC, kbooz commented on apps/website/components/molecules/gates-card.tsx
> +      text: 'Edit',
put content on locales

2022-09-09 14:56 UTC, kbooz commented on apps/website/components/molecules/gates-card.tsx
> +          : 'Unpublish',
put content on locales

2022-09-09 14:56 UTC, kbooz commented on apps/website/components/molecules/gates-card.tsx
> +        this action cannot be undone.
put content on locales

2022-09-09 14:56 UTC, kbooz commented on apps/website/components/molecules/gates-card.tsx
> +        title="Are you sure you want to delete this credential?"
put content on locales

2022-09-09 14:56 UTC, kbooz commented on apps/website/components/molecules/gates-card.tsx
> +            : 'Are you sure you want to publish this credential?'
put content on locales

2022-09-09 14:56 UTC, kbooz commented on apps/website/components/molecules/gates-card.tsx
> +          published === 'published' ? 'Unpublish' : 'Publish'
put content on locales

2022-09-09 14:56 UTC, kbooz commented on apps/website/components/molecules/gates-card.tsx
> +          : 'Publishing this credential will make it accessible by all users.'}
put content on locales

2022-09-12 12:11 UTC, fbenfraj commented on apps/website/components/molecules/gates-card.tsx
> +            message: 'Credential deleted!',
Done

2022-09-12 12:11 UTC, fbenfraj commented on apps/website/components/molecules/gates-card.tsx
> +                : 'unpublished!'
Done

2022-09-12 12:11 UTC, fbenfraj commented on apps/website/components/molecules/gates-card.tsx
> +      text: 'Delete',
Done

2022-09-12 12:11 UTC, fbenfraj commented on apps/website/components/molecules/gates-card.tsx
> +      text: 'Edit',
Done

2022-09-12 12:11 UTC, fbenfraj commented on apps/website/components/molecules/gates-card.tsx
> +          : 'Unpublish',
Done

2022-09-12 12:11 UTC, fbenfraj commented on apps/website/components/molecules/gates-card.tsx
> +        this action cannot be undone.
Done

2022-09-12 12:11 UTC, fbenfraj commented on apps/website/components/molecules/gates-card.tsx
> +        title="Are you sure you want to delete this credential?"
Done

2022-09-12 12:12 UTC, fbenfraj commented on apps/website/components/molecules/gates-card.tsx
> +            : 'Are you sure you want to publish this credential?'
Done

2022-09-12 12:12 UTC, fbenfraj commented on apps/website/components/molecules/gates-card.tsx
> +          published === 'published' ? 'Unpublish' : 'Publish'
Done

2022-09-12 12:12 UTC, fbenfraj commented on apps/website/components/molecules/gates-card.tsx
> +          : 'Publishing this credential will make it accessible by all users.'}
Done

2022-10-07 18:52 UTC, kbooz approved these changes

2022-10-07 19:16 UTC, merged