Feat/twitter follow profile
Gateway-DAO/ui pull request #167
Opened 2022-09-20 19:58 UTC by rafagomes

# Twitter follow Task

## Type of PR

- [] - feature

## Description
A feature that allows the user to verify if he followed the credential task twitter.

2022-09-20 20:33 UTC, kbooz requested changes

2022-09-20 20:33 UTC, kbooz commented on apps/website/components/molecules/add-task/twitter-follow-profile/twitter-follow-profile.tsx
> +  const getTwitterData = async () => {
Use react-query for handling the data and the loading state

2022-09-20 20:33 UTC, kbooz commented on apps/website/components/molecules/add-task/twitter-follow-profile/twitter-follow-profile.tsx
> +            <Typography variant="subtitle2">Follow Profile</Typography>
put content on locale

2022-09-20 20:33 UTC, kbooz commented on apps/website/components/organisms/gates/view/tasks/content/twitter-follow.tsx
> +  const getTwitterData = async () => {
use react-query to handle data fetch

2022-09-20 20:33 UTC, kbooz commented on apps/website/components/organisms/gates/view/tasks/content/twitter-follow.tsx
> +      console.log(error);
console log

2022-09-20 20:33 UTC, kbooz commented on apps/website/components/organisms/gates/view/tasks/content/twitter-follow.tsx
> +  const connectTwitter = async () => {
use react-query to handle data fetch

2022-09-20 20:33 UTC, kbooz commented on apps/website/components/organisms/gates/view/tasks/content/twitter-follow.tsx
> +      const twitter = JSON.parse(window.localStorage.getItem('twitter'));
`react-use` has a way to handle localStorage
https://github.com/streamich/react-use/blob/master/docs/useLocalStorage.md

2022-09-20 20:33 UTC, kbooz commented on apps/website/components/organisms/gates/view/tasks/content/twitter-follow.tsx
> +                    Following
content on locale

2022-09-20 20:33 UTC, kbooz commented on apps/website/pages/following.tsx
> +export default function RedirectPage() {
wound't it be better if this page url would be smth like `/oauth/twitter`, for managing other callbacks

2022-09-20 20:33 UTC, kbooz commented on apps/website/pages/following.tsx
> +  useEffect(() => {
use react-query and useLocalStorage to handle this

2022-09-21 20:26 UTC, rafagomes commented on apps/website/components/molecules/add-task/twitter-follow-profile/twitter-follow-profile.tsx
> +            <Typography variant="subtitle2">Follow Profile</Typography>
will do on a future PR

2022-09-21 20:27 UTC, rafagomes commented on apps/website/components/organisms/gates/view/tasks/content/twitter-follow.tsx
> +                    Following
on a future PR

2022-09-21 22:55 UTC, kbooz requested changes

2022-09-21 22:55 UTC, kbooz commented on apps/website/components/molecules/add-task/twitter-follow-profile/twitter-follow-profile.tsx
> +  const getTwitterData = useQuery(
if this is being called later, use a useMutation instead

2022-09-21 22:55 UTC, kbooz commented on apps/website/components/molecules/add-task/twitter-follow-profile/twitter-follow-profile.tsx
> +    debounce(() => getTwitterData.refetch(), 500),
change getTwitterData to a `useMutation` and call `.mutate()` instead

2022-09-21 22:55 UTC, kbooz commented on apps/website/components/organisms/gates/view/tasks/content/twitter-follow.tsx
> +  const checkTwitterFollow = useQuery(
change this to a `useMutation`

2022-09-21 22:55 UTC, kbooz commented on apps/website/components/organisms/gates/view/tasks/content/twitter-follow.tsx
> +  const connectTwitter = useQuery(
change this to a `useMutation`

2022-10-06 16:32 UTC, merged