Fix drop image field
Gateway-DAO/ui pull request #169
Opened 2022-09-21 12:52 UTC by R11manish

- [x] - bugfix
- [x] - chore

- [ASANA LINK](https://app.asana.com/0/1202770668722101/1202983370735500/f)

2022-09-21 15:15 UTC, kbooz requested changes

2022-09-21 15:15 UTC, kbooz commented on apps/website/components/molecules/image-drop-field/placeholder.tsx
> +        File supported: JPG, PNG, GIF, SVG Max size: 5 MB
put content on locale

2022-09-21 15:15 UTC, kbooz commented on apps/website/components/molecules/image-drop-field/image-drop-field.tsx
> +              hasImage: !!value,
you also need to modify the `EditDropdownMenu`. hasImage is a conditinal, but since now the component is only being rendered when has a value, the stylings that are being applied on it should always appear

2022-09-22 13:33 UTC, kbooz requested changes

2022-09-22 13:33 UTC, kbooz commented on apps/website/components/molecules/image-drop-field/edit-dropdown-menu.tsx
> +        <Avatar>
readd missing stylings

2022-09-22 13:33 UTC, kbooz commented on apps/website/components/molecules/image-drop-field/edit-dropdown-menu.tsx
> -          <MenuItem onClick={withOnClose(onReset)}>
readd missing menuItem

2022-09-23 12:50 UTC, NunoMartins21 approved these changes
Approved, but keeping in mind the changes that Lucas has requested

2022-10-07 18:50 UTC, kbooz approved these changes

2022-10-07 18:50 UTC, merged