Fixes/tweaks
Gateway-DAO/ui pull request #225
Opened 2022-10-14 13:06 UTC by R11manish

- [x] - bugfix
- [x ] - backlog 

### Bugs
- https://app.asana.com/0/1202770668722101/1203065755529415/f
- https://app.asana.com/0/1202770668722101/1203065755529422/f
- https://app.asana.com/0/1202770668722101/1203101053767533/f
- https://app.asana.com/0/1202836314666887/1203136145062230/f

2022-10-14 13:33 UTC, boscocg approved these changes

2022-10-14 14:27 UTC, kbooz requested changes

2022-10-14 14:27 UTC, kbooz commented on apps/website/components/organisms/gates/create/gate-published.tsx
> +                sx={{ mt: {xs : 6 , md : 2} }}
put the margin on the stack container

2022-10-14 14:27 UTC, kbooz commented on apps/website/components/templates/explore/explore.tsx
> -        key: 'people',
this was already planned for this sprint? it wasn't on asana

2022-10-17 12:36 UTC, R11manish commented on apps/website/components/templates/explore/explore.tsx
> -        key: 'people',
it is already mentioned on asana ser

2022-10-18 18:19 UTC, NunoMartins21 approved these changes

2022-10-18 18:20 UTC, merged