Redesign/new task
Gateway-DAO/ui pull request #248
Opened 2022-10-28 05:57 UTC by R11manish

# [PR Name]

## Type of PR

- [x] - feature
- [x] - refactor

- new figma design and refactoring

2022-11-03 14:31 UTC, rafagomes requested changes

2022-11-03 14:31 UTC, rafagomes commented on apps/website/components/atoms/task-icon.tsx
> +export type TaskType =
move this types to the types.ts file. As it is too many lines.

2022-11-03 14:31 UTC, rafagomes commented on apps/website/components/atoms/task-icon.tsx
> +    switch (type) {
I would suggest changing the switch to object handler, it is less complex to machine.

const types = {
'self_verify': InsertLinkIcon
}

return types[value] || null.
something like that

2022-11-24 00:02 UTC, NunoMartins21 approved these changes

2022-11-24 00:02 UTC, merged