Feature/search
Gateway-DAO/ui pull request #31
Opened 2022-07-12 18:03 UTC by NunoMartins21

# Search Page

## Type of PR

- [x] - feature

## Description

Search page for the website. Capable of searching DAOs, gates and users. Interface based on the Explorer page.

## Checklist

- [x] - Built the page according to the Figmas
- [x] - Reviewed with designers; check the bugs

2022-07-13 17:43 UTC, kbooz requested changes
LGTM, only 2 things 😌

2022-07-13 17:43 UTC, kbooz commented on apps/website/constants/categories.ts
> +export const CATEGORIES = {
I would rather put this is in a `dao.ts` and `gate.ts` file 🤔

2022-07-14 13:46 UTC, NunoMartins21 commented on apps/website/constants/categories.ts
> +export const CATEGORIES = {
Hmm okay, well said. I didn't think about it to be honest, but thanks for the idea

2022-07-15 11:16 UTC, fbenfraj approved these changes
LGTM ✅ 😄

2022-07-15 14:21 UTC, Ashishgy commented
No changes are required!

2022-07-18 13:31 UTC, merged