Fix/dao-qa
Gateway-DAO/ui pull request #43
Opened 2022-07-25 16:14 UTC by kbooz

# [PR Name]

## Type of PR

- [] - feature
- [] - bugfix
- [] - chore
- [] - docs

## Description

- Disable the follow button of the DAO card on Explore, if I am admin
- The DAO profile should have at least one category. Define this field as required on create/edit DAO profile.
- Every place which is displayed user and follow button, change the "follow" to "connect"
[DAO PROFILE]
- If a user is admin, it should appear a create gate button on the gates list

## Checklist

- [x] - Provided useful description for this PR
- [x] - Provided the root cause of this bugfix
- [x] - Tested on supported devices

2022-07-25 21:08 UTC, NunoMartins21 commented on apps/website/components/molecules/dao-card.tsx
> +      )}
This is not working (see https://i.imgur.com/Bz0HHlD.png and comments send on private chat).

2022-07-25 21:31 UTC, NunoMartins21 requested changes
Overall I would say everything looks good, *except* the things on which I commented. Minor things to fix though, I believe!

2022-07-25 21:31 UTC, NunoMartins21 commented on apps/website/components/molecules/dao-card.tsx
> +      )}
This is not working (see https://i.imgur.com/Bz0HHlD.png and comments sent on private chat).

2022-07-25 21:31 UTC, NunoMartins21 commented on apps/website/pages/gate/new.tsx
> +  }, []);
If I was to, let's say, be on `/gate/new?dao=4493f46f-6833-4dff-8204-142da8e4c9ae` and refresh for some reason, it would redirect me back to `/home` even if I was on that page correctly first.

My point being: this redirects me to `/home` if I refresh, for no reason.

2022-07-27 13:39 UTC, kbooz commented on apps/website/components/molecules/dao-card.tsx
> +      )}
fixed, checking based on the logged user information, instead of DAO

2022-07-27 13:54 UTC, kbooz commented on apps/website/pages/gate/new.tsx
> +  }, []);
fixed, verified if the route is ready before checcking if route query exists

2022-07-27 23:10 UTC, rafagomes approved these changes

2022-07-27 23:29 UTC, merged