Feat/publish-gate-qa
Gateway-DAO/ui pull request #63
Opened 2022-07-28 20:53 UTC by NunoMartins21

# [PR Name]

## Type of PR

- [x] - feature
- [x] - bugfix
- [x] - chore

## Description

Fixed some bugs mainly related to the Publish Gate flow, but also some other minor things that I found across the website

## Checklist

- [x] - Provided useful description for this PR
- [] - Provided the root cause of this bugfix
- [x] - Tested on supported devices

2022-07-28 21:12 UTC, fbenfraj approved these changes
Lot of cool changes! 😄 LGTM ✅

2022-07-28 22:07 UTC, kbooz requested changes

2022-07-28 22:07 UTC, kbooz commented on apps/website/components/templates/dao-profile/tabs/people-tab/user-cell.tsx
> +          cursor: 'pointer',
don't need cursor pointer if stack is an anchor

2022-07-28 22:07 UTC, kbooz commented on apps/website/components/templates/dao-profile/tabs/people-tab/user-cell.tsx
> +          <Stack alignItems="center" direction="row" gap={1}>
put `<Stack component="a"`

2022-07-29 15:20 UTC, kbooz requested changes

2022-07-29 15:20 UTC, kbooz commented on apps/website/components/templates/dao-profile/tabs/people-tab/user-cell.tsx
> +          <Stack alignItems="center" direction="row" gap={1}>
add `component="a"`

2022-07-29 15:56 UTC, merged