Feat: View Credential
Gateway-DAO/ui pull request #68
Opened 2022-07-29 16:34 UTC by fbenfraj

# Feat: View Credential

## Type of PR
- [✅ ] - feature

## Description
Click on a credential on the profile to access its page.

2022-07-29 17:28 UTC, kbooz requested changes

2022-07-29 17:28 UTC, kbooz commented on apps/website/components/molecules/mint-card/screen/default-mint-screen.tsx
> +        onClick={() => router.push(`/credential/${details.id}`)}
instead of onclick, wrap the component on an `<CardAction>` and `next/link` `<Link >`

links should be rendered as links on html for SEO

2022-07-29 17:28 UTC, kbooz commented on apps/website/components/templates/credential/credential.tsx
> +          <Avatar
use AvatarFile instead

2022-07-29 17:28 UTC, kbooz commented on apps/website/services/queries/credential.gql
> +        id
pass as `...file`

2022-08-01 13:15 UTC, rafagomes approved these changes

2022-08-01 13:15 UTC, merged