Feat/nav bar drop down
Gateway-DAO/ui pull request #88
Opened 2022-08-04 10:35 UTC by R11manish

# [add on navBar dropdown]

## Type of PR

- [x] - feature
- [x] - bugfix

## Description

https://airtable.com/app1gapmC62c8UJsn/tblwmxXDTHo5Jnlpp/viwd77dIfNTvzi7yw/recgWkz91Z9HrjQ9x?blocks=hide

## Checklist

- [x] - Tested on supported devices

2022-08-04 11:10 UTC, fbenfraj requested changes
Just the import change the rest LGTM 😄 ✅

2022-08-04 11:10 UTC, fbenfraj commented on apps/website/components/organisms/navbar/navbar-avatar.tsx
> +import { useAccount } from 'wagmi';
You can regroup all the imports from wagmi

2022-08-08 09:08 UTC, R11manish commented on apps/website/components/organisms/navbar/navbar-avatar.tsx
> +import { useAccount } from 'wagmi';
ok ser

2022-08-08 09:45 UTC, fbenfraj approved these changes

2022-08-08 12:56 UTC, merged